# Generated by Django 4.2.4 on 2023-08-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicTacToeGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_state", models.CharField(max_length=9)),
                ("current_player", models.CharField(default="X", max_length=1)),
                ("winner", models.CharField(blank=True, max_length=1, null=True)),
                ("is_draw", models.BooleanField(default=False)),
            ],
        ),
    ]
