# Generated by Django 4.2.4 on 2023-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticTacToe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tictactoegame",
            name="board_state",
            field=models.CharField(default="         ", max_length=9),
        ),
    ]
